# Generated by Django 5.2.6 on 2026-08-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='العنوان')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('icon', models.CharField(default='fa-solid fa-heart-pulse', help_text='مثال: fa-solid fa-heart-pulse', max_length=50, verbose_name='أيقونة FontAwesome')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'قيمة',
                'verbose_name_plural': 'قيم المبادرة',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DonationMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم/الوصف')),
                ('number', models.CharField(max_length=100, verbose_name='الرقم')),
                ('category', models.CharField(choices=[('bank', 'حسابات مصرفية'), ('mobile', 'المساهمة عبر الرصيد')], default='bank', max_length=10, verbose_name='الفئة')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'طريقة مساهمة',
                'verbose_name_plural': 'طرق المساهمة',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FieldOfWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='العنوان')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('footer_note', models.CharField(blank=True, default='', max_length=200, verbose_name='سطر سفلي')),
                ('icon', models.CharField(default='fa-solid fa-hand-holding-heart', max_length=50, verbose_name='أيقونة FontAwesome')),
                ('color', models.CharField(default='rose', help_text='rose / amber / blue', max_length=30, verbose_name='اللون (روز/كهرماني/أزرق)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'مجال عمل',
                'verbose_name_plural': 'مجالات العمل',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('photo', 'صورة'), ('video', 'فيديو')], default='photo', max_length=10, verbose_name='النوع')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('subtitle', models.CharField(blank=True, default='', max_length=255, verbose_name='العنوان الفرعي')),
                ('file', models.FileField(blank=True, null=True, upload_to='Gallary/', verbose_name='الملف')),
                ('direct_url', models.CharField(blank=True, default='', help_text='استخدمه للتوافق مع الملفات الموجودة في مجلد Gallary، مثال: Gallary/اسم الملف.jpg', max_length=500, verbose_name='مسار مباشر (اختياري)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('active', models.BooleanField(default=True, verbose_name='ظاهر')),
            ],
            options={
                'verbose_name': 'عنصر معرض',
                'verbose_name_plural': 'معرض الأثر',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='العنوان')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('badge', models.CharField(default='مشروع موسمي', max_length=100, verbose_name='الشارة')),
                ('icon', models.CharField(default='fa-solid fa-moon', max_length=50, verbose_name='أيقونة FontAwesome')),
                ('gradient', models.CharField(default='from-emerald-950 via-slate-900 to-slate-950', max_length=100, verbose_name='درجات الألوان')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'مشروع',
                'verbose_name_plural': 'المشاريع',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='مبادرة فزعة المحتاج الخيرية', max_length=255, verbose_name='اسم الموقع')),
                ('tagline', models.CharField(default='مبادرة خيرية تطوعية', max_length=255, verbose_name='الوصف المختصر')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='الشعار')),
                ('hashtag', models.CharField(default='#يلا_نسندهم', max_length=100, verbose_name='الهاشتاق')),
                ('hero_headline', models.CharField(default='معاً نصنع أثراً… ومعاً نمد يد العون', max_length=255, verbose_name='عنوان الواجهة الرئيسية')),
                ('hero_intro', models.TextField(blank=True, default='', verbose_name='مقدمة الواجهة الرئيسية')),
                ('story_badge', models.CharField(default='قصتنا', max_length=100, verbose_name='شارة القصة')),
                ('story_headline', models.CharField(default='سبع سنوات من العطاء والتكاتف المجتمعي', max_length=255, verbose_name='عنوان القصة')),
                ('story_paragraphs', models.TextField(blank=True, default='', help_text='افصل بين كل فقرة وسطر فارغ', verbose_name='فقرات القصة (افصل بينها بسطر فارغ)')),
                ('mission_title', models.CharField(default='رسالتنا', max_length=100, verbose_name='عنوان الرسالة')),
                ('mission_text', models.TextField(blank=True, default='', verbose_name='نص الرسالة')),
                ('vision_title', models.CharField(default='رؤيتنا', max_length=100, verbose_name='عنوان الرؤية')),
                ('vision_text', models.TextField(blank=True, default='', verbose_name='نص الرؤية')),
                ('whatsapp_link', models.URLField(blank=True, default='', verbose_name='رابط الواتساب')),
                ('facebook_link', models.URLField(blank=True, default='', verbose_name='رابط الفيسبوك')),
                ('donation_name', models.CharField(blank=True, default='', max_length=255, verbose_name='باسم (للتبرع)')),
            ],
            options={
                'verbose_name': 'إعدادات الموقع',
                'verbose_name_plural': 'إعدادات الموقع',
            },
        ),
    ]
