# Generated by Django 5.2.6 on 2026-08-28 11:58

from django.db import migrations


def seed_data(apps, schema_editor):
    SiteSettings = apps.get_model('home', 'SiteSettings')
    CoreValue = apps.get_model('home', 'CoreValue')
    FieldOfWork = apps.get_model('home', 'FieldOfWork')
    Project = apps.get_model('home', 'Project')
    GalleryItem = apps.get_model('home', 'GalleryItem')
    DonationMethod = apps.get_model('home', 'DonationMethod')

    if not SiteSettings.objects.exists():
        SiteSettings.objects.create(
            site_name="مبادرة فزعة المحتاج الخيرية",
            tagline="مبادرة خيرية تطوعية",
            hashtag="#يلا_نسندهم",
            hero_headline="معاً نصنع أثراً… ومعاً نمد يد العون",
            hero_intro="مبادرة تطوعية إنسانية تهدف إلى مساندة المحتاجين والوقوف إلى جانب الأسر والأفراد الذين يمرون بظروف صعبة، من خلال تقديم الدعم والمساعدة في مختلف المجالات الإنسانية والمجتمعية.",
            story_badge="قصتنا",
            story_headline="سبع سنوات من العطاء والتكاتف المجتمعي",
            story_paragraphs="منذ انطلاقة مبادرة فزعة المحتاج الخيرية قبل نحو سبع سنوات، بدأت رسالتنا بفكرة بسيطة وعظيمة في معناها: أن لا يواجه المحتاج أزمته وحده.\n\nوخلال هذه السنوات، واصلت المبادرة جهودها في مساعدة المحتاجين، وإطلاق المبادرات الإنسانية، والاستجابة للحالات الطارئة، وجمع أهل الخير حول هدف واحد؛ وهو تخفيف معاناة الإنسان وصناعة أثر حقيقي في المجتمع.\n\nلم تكن السنوات السبع مجرد فترة زمنية، بل كانت رحلة مليئة بالعطاء، والتحديات، والمواقف الإنسانية التي أكدت لنا أن الخير ما زال موجوداً، وأن تكاتف المجتمع قادر على تغيير حياة إنسان.",
            mission_title="رسالتنا",
            mission_text="نسعى إلى الوصول إلى المحتاجين وتقديم الدعم لهم بكرامة وشفافية، وتشجيع أفراد المجتمع على المشاركة في العمل الخيري والتطوعي، حتى يصبح العطاء ثقافة مستمرة وأثراً يمتد إلى أكبر عدد ممكن من المستفيدين.",
            vision_title="رؤيتنا",
            vision_text="أن نكون جسراً موثوقاً بين أهل الخير والمحتاجين، وأن نساهم في بناء مجتمع أكثر تكافلاً ورحمة، يشعر فيه كل محتاج أن هناك من يقف إلى جانبه.",
            whatsapp_link="https://chat.whatsapp.com/JxMWrPjswZoGB5IoP1OgFv?s=cl&p=a&ilr=0",
            facebook_link="https://facebook.com/groups/971459819951254/",
            donation_name="آلاء عبدالرحمن",
        )

    if not CoreValue.objects.exists():
        CoreValue.objects.bulk_create([
            CoreValue(title="الرحمة", description="نضع الإنسان واحتياجه في مقدمة أولوياتنا دون تمييز.", icon="fa-solid fa-heart-pulse", order=1),
            CoreValue(title="الأمانة", description="نحافظ على ثقة المتبرعين والمستفيدين بكل إخلاص.", icon="fa-solid fa-shield-halved", order=2),
            CoreValue(title="الشفافية", description="نحرص على الوضوح التام في كافة أعمالنا ومشاريعنا.", icon="fa-solid fa-glasses", order=3),
            CoreValue(title="التكافل", description="نؤمن أن العمل الخيري مسؤولية مشتركة لجميع أفراد المجتمع.", icon="fa-solid fa-people-hold", order=4),
            CoreValue(title="الكرامة", description="نقدم المساعدة بما يحفظ كرامة وخصوصية المستفيد تماماً.", icon="fa-solid fa-user-shield", order=5),
            CoreValue(title="الأثر", description="لا نبحث فقط عن تقديم المساعدة، بل عن صناعة أثر حقيقي ومستمر.", icon="fa-solid fa-chart-line", order=6),
        ])

    if not FieldOfWork.objects.exists():
        FieldOfWork.objects.bulk_create([
            FieldOfWork(title="الحوجات العلاجية", description="نساهم في توفير تكاليف العلاج والأدوية والفحوصات للحالات التي تحتاج إلى الدعم، ونسعى لأن لا يكون العجز المادي سبباً في حرمان أي محتاج من العلاج.", footer_note="رعاية صحية وتكفل", icon="fa-solid fa-notes-medical", color="rose", order=1),
            FieldOfWork(title="سداد الديون", description="نساعد في تفريج كربة الغارمين وأصحاب الديون الذين يمرون بظروف صعبة، من خلال المساهمة في سداد ما عليهم وفقاً للحالات التي يتم اعتمادها.", footer_note="تفريج كرب الغارمين", icon="fa-solid fa-handshake-angle", color="amber", order=2),
            FieldOfWork(title="حوجات الطلبة", description="ندعم الطلاب والطالبات المحتاجين، ونساهم في توفير احتياجاتهم التعليمية لمساعدتهم على مواصلة دراستهم وتحقيق أهدافهم.", footer_note="دعم المسيرة التعليمية", icon="fa-solid fa-graduation-cap", color="blue", order=3),
        ])

    if not Project.objects.exists():
        Project.objects.bulk_create([
            Project(title="سلة رمضان", description="مشروع موسمي يهدف إلى توفير السلال الغذائية للأسر المحتاجة خلال شهر رمضان، ومشاركتهم فرحة الشهر الكريم والتخفيف من أعبائهم المعيشية.", badge="مشروع موسمي", icon="fa-solid fa-moon", gradient="from-emerald-950 via-slate-900 to-slate-950", order=1),
            Project(title="فرحة عيد", description="نسعى من خلال هذا المشروع إلى إدخال الفرحة إلى قلوب الأسر والأطفال المحتاجين في الأعياد، من خلال توفير الاحتياجات والمساهمات التي تساعدهم على استقبال العيد بفرحة وكرامة.", badge="مشروع موسمي", icon="fa-solid fa-gift", gradient="from-slate-900 via-emerald-950 to-slate-950", order=2),
        ])

    if not GalleryItem.objects.exists():
        GalleryItem.objects.bulk_create([
            GalleryItem(media_type='photo', title="تجهيز وتوزيع السلال الغذائية الرمضانية", direct_url="Gallary/WhatsApp Image 2026-08-27 at 9.42.35 PM.jpeg", order=1),
            GalleryItem(media_type='photo', title="مشاريع العطاء والإغاثة الميدانية", direct_url="Gallary/WhatsApp Image 2026-08-27 at 9.42.36 PM (1).jpeg", order=2),
            GalleryItem(media_type='photo', title="توصيل المساعدات للأسر المتعففة", direct_url="Gallary/WhatsApp Image 2026-08-27 at 9.42.36 PM (2).jpeg", order=3),
            GalleryItem(media_type='photo', title="وقفات التكاتف والمساندة المجتمعية", direct_url="Gallary/WhatsApp Image 2026-08-27 at 9.42.36 PM.jpeg", order=4),
            GalleryItem(media_type='photo', title="تأمين الاحتياجات الأساسية للمحتاجين", direct_url="Gallary/WhatsApp Image 2026-08-27 at 9.42.38 PM.jpeg", order=5),
            GalleryItem(media_type='photo', title="إشراف وتنسيق فريق فزعة المحتاج", direct_url="Gallary/WhatsApp Image 2026-08-27 at 9.42.38 PM (1).jpeg", order=6),
            GalleryItem(media_type='video', title="توثيق تسليم وتوزيع المساعدات الميدانية", subtitle="#يلا_نسندهم - مبادرة فزعة المحتاج", direct_url="Gallary/WhatsApp Video 2026-08-27 at 9.42.33 PM.mp4", order=7),
            GalleryItem(media_type='video', title="مراحل إعداد السلال والطرود الخيرية", subtitle="#يلا_نسندهم - مبادرة فزعة المحتاج", direct_url="Gallary/WhatsApp Video 2026-08-27 at 9.42.33 PM (1).mp4", order=8),
            GalleryItem(media_type='video', title="استجابة المبادرة للحالات الميدانية العاجلة", subtitle="#يلا_نسندهم - مبادرة فزعة المحتاج", direct_url="Gallary/WhatsApp Video 2026-08-27 at 9.42.33 PM (2).mp4", order=9),
            GalleryItem(media_type='video', title="فرحة المستفيدين وتوثيق إنجازات العطاء", subtitle="#يلا_نسندهم - مبادرة فزعة المحتاج", direct_url="Gallary/WhatsApp Video 2026-08-27 at 9.42.34 PM.mp4", order=10),
        ])

    if not DonationMethod.objects.exists():
        DonationMethod.objects.bulk_create([
            DonationMethod(name="تطبيق بنكك (Bankak)", number="3023848", category='bank', order=1),
            DonationMethod(name="تطبيق فوري (Fawry)", number="51618095", category='bank', order=2),
            DonationMethod(name="أريبا (Areeba)", number="0990823331", category='mobile', order=3),
            DonationMethod(name="سوداني (Sudani)", number="0119841566", category='mobile', order=4),
        ])


def unseed_data(apps, schema_editor):
    for model in ['SiteSettings', 'CoreValue', 'FieldOfWork', 'Project', 'GalleryItem', 'DonationMethod']:
        apps.get_model('home', model).objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_data, unseed_data),
    ]
