# Generated by Django 5.2.6 on 2026-08-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_seed_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='الاسم الكامل')),
                ('phone', models.CharField(max_length=50, verbose_name='رقم الجوال / واتساب')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='البريد الإلكتروني')),
                ('city', models.CharField(blank=True, default='', max_length=100, verbose_name='المدينة')),
                ('interest', models.TextField(blank=True, default='', help_text='مثال: العمل الميداني، التواصل، التصوير، الطب، التقنية...', verbose_name='مجالات الاهتمام أو الخبرات')),
                ('availability', models.CharField(blank=True, default='', max_length=200, verbose_name='أوقات التوفر')),
                ('message', models.TextField(blank=True, default='', verbose_name='رسالة إضافية')),
                ('status', models.CharField(choices=[('new', 'جديد'), ('contacted', 'تم التواصل'), ('accepted', 'مقبول'), ('rejected', 'مرفوض')], default='new', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التقديم')),
            ],
            options={
                'verbose_name': 'طلب تطوع',
                'verbose_name_plural': 'طلبات التطوع',
                'ordering': ['-created_at'],
            },
        ),
    ]
